# @package _global_

defaults:
  - humanoid

# Env structure
env:
  _target_: phys_anim.envs.path_following.${backbone}.PathFollowingHumanoid
  config:
    enable_height_termination: False
    max_episode_length: 300

    path_follower_params:
      num_traj_samples: 10
      fail_dist: 4.
      fail_height_dist: 0.5
      traj_sample_timestep: 0.5
      path_generator:
        num_verts: 101
        dtheta_max: 2.
        sharp_turn_prob: 0.02
        accel_max: 2.
        speed_max: 5.
        speed_min: 0.
        fixed_path: False
        slow: False
        height_conditioned: ${..height_conditioned}
        start_speed_max: 3.
        head_change_max: 0.05
        head_height_max: 1.5
        head_height_min: 0.4
        use_naive_path_generator: False
      path_obs_size: ${eval:${.num_path_obs_per_point}*${.num_traj_samples}}
      enable_path_termination: True
      height_conditioned: True
      num_path_obs_per_point: ${eval:${.height_conditioned}*1+2}

eval_overrides:
  env:
    config:
      max_episode_length: 300
      path_follower_params:
        enable_path_termination: False
