# @package _global_

defaults:
  - /agent/mimic/agent_amp
  - /env/mimic

  - /agent/ppo/models/transformer_actor
  - /agent/ppo/models/mlp_critic_large
  - /agent/amp/models/mlp_discriminator_large
  - /agent/mimic/models/transformer_actor_target_pose
  - /agent/mimic/models/mlp_critic_target_pose
  - /terrain/complex
  - /agent/ppo/models/transformer_actor_terrain
  - /agent/ppo/models/mlp_critic_terrain
  # # - /scenes/samp
  - /agent/mimic/options/global_tracking
  - /agent/mimic/options/early_termination_tracking_err
  - /agent/mimic/options/dynamic_sampling

env:
  config:
    mimic_target_pose:
      type: max-coords-future-rel
      with_time: true
      num_future_steps: 15
    humanoid_obs:
      num_historical_steps: 8
