# @package _global_

defaults:
  - /algo: mimic
  - /env: mimic
  - /opt/disable_discriminator  # Default mimic experiments don't use the discriminator
  - /terrain/terrain_obs
  - /terrain/complex
  - /scenes/samp
  - /opt/mimic/transformer/target_pose_with_time_obs
  - /opt/mimic/global_tracking
  - /opt/mimic/early_termination_tracking_err
  - /opt/mimic/dynamic_sampling

experiment_name: full_body_tracker