# @package _global_

fabric:
  _target_: lightning.fabric.Fabric
  _convert_: all
  accelerator: gpu
  devices: ${ngpu}
  num_nodes: ${nodes}
  strategy:
    _target_: lightning.fabric.strategies.DDPStrategy
  precision: ${amp_precision}
  loggers:
    - _target_: lightning.fabric.loggers.TensorBoardLogger
      root_dir: ${save_dir}

# These are global variables that all levels of the config can access.
## Compute setup
ngpu: 1
nodes: 1
torch_deterministic: False
amp_precision: 32-true
force_flat_terrain: False

eval_overrides:
  ngpu: 1
  nodes: 1

  fabric:
    loggers: null
