# @package _global_

defaults:
  - amp

robot:
  # Observation parameters
  dof_obs_size: 78
  number_of_actions: 31
  self_obs_max_coords_size: 253  # ${eval:1+17*(3+6+3+3)-3}

  # Control parameters
  isaacgym_body_names: ['pelvis', 'torso', 'head', 'right_upper_arm', 'right_lower_arm', 'right_hand', 'sword', 'left_upper_arm', 'left_lower_arm', 'shield', 'left_hand', 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot']
  isaacgym_dof_names: ['abdomen_x', 'abdomen_y', 'abdomen_z', 'neck_x', 'neck_y', 'neck_z', 'right_shoulder_x', 'right_shoulder_y', 'right_shoulder_z', 'right_elbow', 'right_hand_x', 'right_hand_y', 'right_hand_z', 'left_shoulder_x', 'left_shoulder_y', 'left_shoulder_z', 'left_elbow', 'right_hip_x', 'right_hip_y', 'right_hip_z', 'right_knee', 'right_ankle_x', 'right_ankle_y', 'right_ankle_z', 'left_hip_x', 'left_hip_y', 'left_hip_z', 'left_knee', 'left_ankle_x', 'left_ankle_y', 'left_ankle_z']

  isaacgym_dof_body_ids: [ 1, 2, 3, 4, 5, 7, 8, 11, 12, 13, 14, 15, 16 ]

  key_bodies:
    - "sword"
    - "shield"

  asset:
    robot_type: amp_humanoid_sword_shield
